language: node_js
sudo: true

script:
- sudo apt-get install fuse appstream appstream-util git jq patch libxkbfile-dev libgles2-mesa-dev libsecret-1-dev
- nvm install v12.18.0
- nvm use v12.18.0
- curl -o- -L https://yarnpkg.com/install.sh | bash
- export PATH="$HOME/.yarn/bin:$HOME/.config/yarn/global/node_modules/.bin:$PATH"
- mkdir bin; cd bin
- curl -L https://github.com/AppImage/AppImageKit/releases/download/continuous/appimagetool-x86_64.AppImage
  -o appimagetool; chmod +x appimagetool
- curl -L https://github.com/probonopd/linuxdeployqt/releases/download/7/linuxdeployqt-7-x86_64.AppImage
  -o linuxdeployqt; chmod +x linuxdeployqt
- cd ..
- BUILD_SRCDIR="$(pwd)"
- git clone https://github.com/Microsoft/vscode
- cd vscode
- git checkout 1.48.2
- patch -i ../product.json.patch
- yarn preinstall
- yarn install
- yarn gulp vscode-linux-x64
- yarn postinstall
- cd ..
- gpg --import ~/appsign.asc
- mkdir AppDir
- BUILD_HOME="$(pwd)"
- BUILD_APPDIR="${BUILD_HOME}/AppDir"
- mkdir -p "${BUILD_APPDIR}/usr/share/metainfo"
- mkdir -p "${BUILD_APPDIR}/usr/share/icons/hicolor/scalable/apps"
- mkdir -p "${BUILD_APPDIR}/usr/share/applications"
- mkdir -p "${BUILD_APPDIR}/usr/bin"
- cp code-oss.svg "${BUILD_APPDIR}/usr/share/icons/hicolor/scalable/apps"
- cp code-oss.svg "${BUILD_APPDIR}"
- cp code-oss.desktop "${BUILD_APPDIR}/usr/share/applications"
- cp code-oss.desktop "${BUILD_APPDIR}"
- chmod +x AppRun
- mv VSCode-linux-x64 "${BUILD_APPDIR}/usr/share/code-oss"
- cp "${BUILD_SRCDIR}/vscode/resources/linux/code.png" "${BUILD_APPDIR}/usr/share/code-oss/code-oss.png"
- cp "${BUILD_SRCDIR}/vscode/resources/linux/code.png" "${BUILD_APPDIR}/code-oss.png"
- cd "${BUILD_APPDIR}/usr/bin"
- ln -s ../share/code-oss/code-oss "code-oss"
- cd "${BUILD_HOME}"
- rm "${BUILD_APPDIR}/usr/share/code-oss/bin/code-oss"
- export SIGN=1
- export ARCH=x86_64
- export UPDATE_INFORMATION="gh-releases-zsync|zilti|code-oss.AppImage|continuous|Code*.AppImage.zsync"
- export CODIR="${BUILD_APPDIR}/usr/share/code-oss"
- |
  bin/linuxdeployqt AppDir/usr/share/applications/code-oss.desktop \
  -updateinformation "gh-releases-zsync|zilti|code-oss.AppImage|continuous|Code*.AppImage.zsync"
  -appimage
- wget -c https://github.com/probonopd/uploadtool/raw/master/upload.sh
- bash upload.sh ./*.AppImage*

before_install:
- openssl aes-256-cbc -K $encrypted_36aeddb2b26d_key -iv $encrypted_36aeddb2b26d_iv
  -in appsign.asc.enc -out ~/appsign.asc -d
